FROM node:20-apline AS deps
WORKDIR /app
COPY package.json package.json* ./
RUN npm install

FROM node:20-apline AS build
WORKDIR /app
COPY . .
RUN npm run build

FROM node:20-apline AS prod
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY package.json ./
EXPOSE 8000
CMD ["RUN","dist/index.js"]